dist: trusty
sudo: required
language: python
python:
  - "3.6"
branches:
    only:
    - /.*/
before_install:
    - sudo apt-get update
install:
    - sudo apt-get -y install build-essential checkinstall
    - sudo apt-get -y install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
    - sudo apt-get -y install mongodb
    - pip install --upgrade pip
    - sudo pip install -r requirements.txt
before_script:
    - mkdir /tmp/mongo_dir
    - mongod --dbpath /tmp/mongo_dir &
script:
    - python3 -m unittest
