dist: xenial
sudo: required
language: python
python:
- "3.6"
cache: pip
branches:
    only:
    - /.*/
before_install:
    - sudo apt-get update
install:
    - sudo apt-get -y mongodb
    - pip install --upgrade pip
    - pip install -r requirements.txt
before_script:
    - mkdir -p /tmp/mongo/data
    - mkdir -p /tmp/mongo/logs
    - mongod --dbpath /tmp/mongo/data --fork --logpath /tmp/mongo/logs
script:
    - python -m unittest
