language: python
branches:
    only:
        develop
before_install:
    - sudo apt-get update
install:
    - sudo apt-get -y install python3 mongod
    - sudo python3 -m pip install -r requirements.txt
script:
    - python3 -m unittest

