dist: xenial
sudo: required

language: python
python:
- "2.7"
- "3.5"
- "3.6"
- "3.7"

.mixins:
- &trusty-mixin
  dist: trusty
  sudo:
jobs:
  include:
  - <<: *trusty-mixin
    python: "3.3"
  - <<: *trusty-mixin
    python: "3.4"
  - <<: *trusty-mixin
    python: "pypy"
branches:
    only:
    - /.*/
before_install:
    - sudo apt-get update
install:
    - sudo apt-get -y install build-essential checkinstall
    - sudo apt-get -y install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
    - sudo apt-get -y install mongodb
    - pip install --upgrade pip
    - sudo pip install -r requirements.txt
before_script:
    - mkdir /tmp/mongo_dir
    - mongod --dbpath /tmp/mongo_dir &
script:
    - python3 -m unittest
