language: python
python:
  - "3.6"
branches:
    only:
    - /.*/
before_install:
    - sudo apt-get update
install:
    - sudo apt-get -y install mongodb
    - sudo pip install -r requirements.txt
script:
    - python3 -m unittest
