# We need xenial otherwise we will get an ssl error with tornado install
dist: xenial
sudo: required
language: python
python:
    - "3.6"
services:
    - mongodb
cache: pip
branches:
    only:
    - /.*/
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
script:
    - black --check broadway_api/ tests/
    - flake8 --count --config=setup.cfg
    - py.test -v --cov=broadway_api/ tests/ --cov coveralls --cov-report term-missing --doctest-modules
after_success:
    - coveralls
