API_HOSTNAME = "127.0.0.1"
API_PORT = 1470
API_PROXY = ""
LOGS_DIR = "logs"
VERBOSE = True
TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"
SUCCESS_CODE = 200
QUEUE_EMPTY_CODE = 498
HEARTBEAT_INTERVAL = 10
JOB_POLL_INTERVAL = 5

# API endpoints
USE_SSL = True
HEARTBEAT_ENDPOINT = "/api/v1/heartbeat"
GRADING_JOB_ENDPOINT = "/api/v1/grading_job"
GRADER_REGISTER_ENDPOINT = "/api/v1/worker"
