# The documents stored in the Mongo DB use these keys

ID = "_id"
LAST_SEEN = "last_seen"
RUNNING_JOB = "running_job_id"
CREATED = "created_at"
QUEUED = "queued_at"
STARTED = "started_at"
FINISHED = "finished_at"
STUDENTS = "students"
STUDENT_JOBS = "student_job_ids"
PRE_PROCESSING = "pre_processing_job_id"
POST_PROCESSING = "post_processing_job_id"
STUDENT_JOBS_LEFT = "student_jobs_left"
RESULTS = "results"
SUCCESS = "success"
GRADING_RUN = "grading_run_id"
STAGES = "stages"
JOB_ID = "job_id"
WORKER_HOSTNAME = "worker_hostname"
TOKEN = "token"
TOKEN_IDS = "token_ids"
