LOGS_DIR = "logs"
ID_REGEX = "(?P<id_>[a-f0-9]+)"
TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"

# API KEYS
AUTH_KEY = "Authorization"
WORKER_ID_KEY = "worker_id"
HEARTBEAT_KEY = "heartbeat"

# DATABASE KEYS
ID_KEY = "_id"
LAST_SEEN_KEY = "last_seen"
RUNNING_JOBS_KEY = "running_job_ids"
CREATED_KEY = "created_at"
QUEUED_KEY = "queued_at"
STARTED_KEY = "started_at"
FINISHED_KEY = "finished_at"
STUDENTS_KEY = "students"
STUDENT_JOBS_KEY = "student_job_ids"
PRE_PROCESSING_KEY = "pre_processing_job_id"
POST_PROCESSING_KEY = "post_processing_job_id"
STUDENT_JOBS_LEFT = "student_jobs_left"
RESULT_KEY = "result"
GRADING_RUN_KEY = "grading_run_id"
STAGES_KEY = "stages"
